import {Injectable} from '@angular/core';
import {AngularFirestore, DocumentReference} from '@angular/fire/firestore';
import {Observable} from 'rxjs';
import {WordList} from 'types';

@Injectable({providedIn: 'root'})
export class WordListsService {
    constructor(
        private afs: AngularFirestore,
    ) {
    }

    private originalWords = [
        'AFRICA', 'AGENT', 'AIR', 'ALIEN', 'ALPS',
        'AMAZON', 'AMBULANCE', 'AMERICA', 'ANGEL', 'ANTARCTICA',
        'APPLE', 'ARM', 'ATLANTIS', 'AUSTRALIA', 'AZTEC',
        'BACK', 'BALL', 'BAND', 'BANK', 'BAR',
        'BARK', 'BAT', 'BATTERY', 'BEACH', 'BEAR',
        'BEAT', 'BED', 'BEIJING', 'BELL', 'BELT',
        'BERLIN', 'BERMUDA', 'BERRY', 'BILL', 'BLOCK',
        'BOARD', 'BOLT', 'BOMB', 'BOND', 'BOOM',
        'BOOT', 'BOTTLE', 'BOW', 'BOX', 'BRIDGE',
        'BRUSH', 'BUCK', 'BUFFALO', 'BUG', 'BUGLE',
        'BUTTON', 'CALF', 'CANADA', 'CAP', 'CAPITAL',
        'CAR', 'CARD', 'CARROT', 'CASINO', 'CAST',
        'CAT', 'CELL', 'CENTAUR', 'CENTER', 'CHAIR',
        'CHANGE', 'CHARGE', 'CHECK', 'CHEST', 'CHICK',
        'CHINA', 'CHOCOLATE', 'CHURCH', 'CIRCLE', 'CLIFF',
        'CLOAK', 'CLUB', 'CODE', 'COLD', 'COMIC',
        'COMPOUND', 'CONCERT', 'CONDUCTOR', 'CONTRACT', 'COOK',
        'COPPER', 'COTTON', 'COURT', 'COVER', 'CRANE',
        'CRASH', 'CRICKET', 'CROSS', 'CROWN', 'CYCLE',
        'CZECH', 'DANCE', 'DATE', 'DAY', 'DEATH',
        'DECK', 'DEGREE', 'DIAMOND', 'DICE', 'DINOSAUR',
        'DISEASE', 'DOCTOR', 'DOG', 'DRAFT', 'DRAGON',
        'DRESS', 'DRILL', 'DROP', 'DUCK', 'DWARF',
        'EAGLE', 'EGYPT', 'EMBASSY', 'ENGINE', 'ENGLAND',
        'EUROPE', 'EYE', 'FACE', 'FAIR', 'FALL',
        'FAN', 'FENCE', 'FIELD', 'FIGHTER', 'FIGURE',
        'FILE', 'FILM', 'FIRE', 'FISH', 'FLUTE',
        'FLY', 'FOOT', 'FORCE', 'FOREST', 'FORK',
        'FRANCE', 'GAME', 'GAS', 'GENIUS', 'GERMANY',
        'GHOST', 'GIANT', 'GLASS', 'GLOVE', 'GOLD',
        'GRACE', 'GRASS', 'GREECE', 'GREEN', 'GROUND',
        'HAM', 'HAND', 'HAWK', 'HEAD', 'HEART',
        'HELICOPTER', 'HIMALAYAS', 'HOLE', 'HOLLYWOOD', 'HONEY',
        'HOOD', 'HOOK', 'HORN', 'HORSE', 'HORSESHOE',
        'HOSPITAL', 'HOTEL', 'ICE', 'ICE CREAM', 'INDIA',
        'IRON', 'IVORY', 'JACK', 'JAM', 'JET',
        'JUPITER', 'KANGAROO', 'KETCHUP', 'KEY', 'KID',
        'KING', 'KIWI', 'KNIFE', 'KNIGHT', 'LAB',
        'LAP', 'LASER', 'LAWYER', 'LEAD', 'LEMON',
        'LEPRECHAUN', 'LIFE', 'LIGHT', 'LIMOUSINE', 'LINE',
        'LINK', 'LION', 'LITTER', 'LOCH NESS', 'LOCK',
        'LOG', 'LONDON', 'LUCK', 'MAIL', 'MAMMOTH',
        'MAPLE', 'MARBLE', 'MARCH', 'MASS', 'MATCH',
        'MERCURY', 'MEXICO', 'MICROSCOPE', 'MILLIONAIRE', 'MINE',
        'MINT', 'MISSILE', 'MODEL', 'MOLE', 'MOON',
        'MOSCOW', 'MOUNT', 'MOUSE', 'MOUTH', 'MUG',
        'NAIL', 'NEEDLE', 'NET', 'NEW YORK', 'NIGHT',
        'NINJA', 'NOTE', 'NOVEL', 'NURSE', 'NUT',
        'OCTOPUS', 'OIL', 'OLIVE', 'OLYMPUS', 'OPERA',
        'ORANGE', 'ORGAN', 'PALM', 'PAN', 'PANTS',
        'PAPER', 'PARACHUTE', 'PARK', 'PART', 'PASS',
        'PASTE', 'PENGUIN', 'PHOENIX', 'PIANO', 'PIE',
        'PILOT', 'PIN', 'PIPE', 'PIRATE', 'PISTOL',
        'PIT', 'PITCH', 'PLANE', 'PLASTIC', 'PLATE',
        'PLATYPUS', 'PLAY', 'PLOT', 'POINT', 'POISON',
        'POLE', 'POLICE', 'POOL', 'PORT', 'POST',
        'POUND', 'PRESS', 'PRINCESS', 'PUMPKIN', 'PUPIL',
        'PYRAMID', 'QUEEN', 'RABBIT', 'RACKET', 'RAY',
        'REVOLUTION', 'RING', 'ROBIN', 'ROBOT', 'ROCK',
        'ROME', 'ROOT', 'ROSE', 'ROULETTE', 'ROUND',
        'ROW', 'RULER', 'SATELLITE', 'SATURN', 'SCALE',
        'SCHOOL', 'SCIENTIST', 'SCORPION', 'SCREEN', 'SCUBA DIVER',
        'SEAL', 'SERVER', 'SHADOW', 'SHAKESPEARE', 'SHARK',
        'SHIP', 'SHOE', 'SHOP', 'SHOT', 'SINK',
        'SKYSCRAPER', 'SLIP', 'SLUG', 'SMUGGLER', 'SNOW',
        'SNOWMAN', 'SOCK', 'SOLDIER', 'SOUL', 'SOUND',
        'SPACE', 'SPELL', 'SPIDER', 'SPIKE', 'SPINE',
        'SPOT', 'SPRING', 'SPY', 'SQUARE', 'STADIUM',
        'STAFF', 'STAR', 'STATE', 'STICK', 'STOCK',
        'STRAW', 'STREAM', 'STRIKE', 'STRING', 'SUB',
        'SUIT', 'SUPERHERO', 'SWING', 'SWITCH', 'TABLE',
        'TABLET', 'TAG', 'TAIL', 'TAP', 'TEACHER',
        'TELESCOPE', 'TEMPLE', 'THEATER', 'THIEF', 'THUMB',
        'TICK', 'TIE', 'TIME', 'TOKYO', 'TOOTH',
        'TORCH', 'TOWER', 'TRACK', 'TRAIN', 'TRIANGLE',
        'TRIP', 'TRUNK', 'TUBE', 'TURKEY', 'UNDERTAKER',
        'UNICORN', 'VACUUM', 'VAN', 'VET', 'WAKE',
        'WALL', 'WAR', 'WASHER', 'WASHINGTON', 'WATCH',
        'WATER', 'WAVE', 'WEB', 'WELL', 'WHALE',
        'WHIP', 'WIND', 'WITCH', 'WORM', 'YARD'
    ];
    private duetWords = [
        'DRUM', 'BRIDE', 'WAGON', 'UNIVERSITY', 'HIT',
        'ASH', 'BASS', 'ASTRONAUT', 'DOLL', 'NERVE',
        'COACH', 'BEAM', 'SPOON', 'COUNTRY', 'NOSE',
        'KING ARTHUR', 'STAMP', 'CAMP', 'BRAIN', 'LEAF',
        'TUTU', 'COAST', 'LUNCH', 'THUNDER', 'POTATO',
        'DESK', 'ONION', 'ELEPHANT', 'ANCHOR', 'COWBOY',
        'FLOOD', 'MOHAWK', 'SANTA', 'PITCHER', 'BARBECUE',
        'LEATHER', 'SKATES', 'MUSKETEER', 'SNAP', 'SADDLE',
        'GENIE', 'MARK', 'SHOULDER', 'GOVERNOR', 'MANICURE',
        'ANTHEM', 'HALLOWEEN', 'NEWTON', 'BALLOON', 'FIDDLE',
        'CRAFT', 'GLACIER', 'CAKE', 'RAT', 'TANK',
        'BLIND', 'SPIRIT', 'CABLE', 'SWAMP', 'EINSTEIN',
        'HIDE', 'CRYSTAL', 'GEAR', 'KISS', 'PEW',
        'POWDER', 'TURTLE', 'BACON', 'SHERLOCK', 'SQUASH',
        'BOOK', 'RAZOR', 'DRESSING', 'BRICK', 'BRAZIL',
        'TEAR', 'STABLE', 'BIKINI', 'PEN', 'ROLL',
        'CHRISTMAS', 'RUBBER', 'BAY', 'MOTHER', 'KICK',
        'FOG', 'RADIO', 'CRAB', 'CONE', 'SKULL',
        'WHEELCHAIR', 'EGG', 'BUTTER', 'WEREWOLF', 'CHERRY',
        'PATIENT', 'DRYER', 'DRAWING', 'BOSS', 'FEVER',
        'BANANA', 'POLISH', 'KNOT', 'PAINT', 'STORM',
        'GOLDILOCKS', 'PILLOW', 'CHAIN', 'MOSES', 'SAW',
        'BROTHER', 'RAIL', 'ROPE', 'STREET', 'PAD',
        'CAPTAIN', 'WISH', 'AXE', 'SHORTS', 'POPCORN',
        'CASTLE', 'SECOND', 'TEAM', 'OASIS', 'MESS',
        'MISS', 'AVALANCHE', 'TEXAS', 'SUN', 'LETTER',
        'RUST', 'WING', 'STEEL', 'EAR', 'SCROLL',
        'BUNK', 'CANE', 'VENUS', 'LADDER', 'PURSE',
        'SHEET', 'NAPOLEON', 'SUGAR', 'DIRECTOR', 'ACE',
        'SCRATCH', 'BUCKET', 'CAESAR', 'DISK', 'BEARD',
        'BULB', 'BENCH', 'SCARECROW', 'IGLOO', 'TUXEDO',
        'EARTH', 'RAM', 'SISTER', 'BREAD', 'RECORD',
        'DASH', 'GREENHOUSE', 'DRONE', 'STEAM', 'BISCUIT',
        'RIP', 'NOTRE DAME', 'LIP', 'SHAMPOO', 'CHEESE',
        'SACK', 'MOUNTIE', 'SUMO', 'SAHARA', 'WALRUS',
        'DUST', 'HAMMER', 'CLOUD', 'SPRAY', 'ST.PATRICK',
        'KILT', 'MONKEY', 'FROG', 'DENTIST', 'RAINBOW',
        'WHISTLE', 'REINDEER', 'KITCHEN', 'LEMONADE', 'SLIPPER',
        'FLOOR', 'VALENTINE', 'PEPPER', 'ROAD', 'SHED',
        'BOWLER', 'MILK', 'WHEEL', 'MAGAZINE', 'BRASS',
        'TEA', 'HELMET', 'FLAG', 'TROLL', 'JAIL',
        'STICKER', 'PUPPET', 'CHALK', 'BONSAI', 'SWEAT',
        'GANGSTER', 'BUTTERFLY', 'STORY', 'SALAD', 'ARMOR',
        'SMOKE', 'CAVE', 'QUACK', 'BREAK', 'SNAKE',
        'MILL', 'GYMNAST', 'WONDERLAND', 'DRIVER', 'SPURS',
        'ZOMBIE', 'PIG', 'CLEOPATRA', 'TOAST', 'PENNY',
        'ANT', 'VOLUME', 'LACE', 'BATTLESHIP', 'MARACAS',
        'METER', 'SLING', 'DELTA', 'STEP', 'JOAN OF ARC',
        'COMET', 'BATH', 'POLO', 'GUM', 'VAMPIRE',
        'SKI', 'POCKET', 'BATTLE', 'FOAM', 'RODEO',
        'SQUIRREL', 'SALT', 'MUMMY', 'BLACKSMITH', 'CHIP',
        'GOAT', 'LAUNDRY', 'BEE', 'TATTOO', 'RUSSIA',
        'TIN', 'MAP', 'YELLOWSTONE', 'SILK', 'HOSE',
        'SLOTH', 'KUNG FU', 'CLOCK', 'BEAN', 'LIGHTNING',
        'BOWL', 'GUITAR', 'RANCH', 'PEARL', 'FLAT',
        'VIRUS', 'ICE AGE', 'COFFEE', 'MARATHON', 'ATTIC',
        'WEDDING', 'COLUMBUS', 'POP', 'SHERWOOD', 'TRICK',
        'NYLON', 'LOCUST', 'PACIFIC', 'CUCKOO', 'TORNADO',
        'MEMORY', 'JOCKEY', 'MINOTAUR', 'BIG BANG', 'PAGE',
        'SPHINX', 'CRUSADER', 'VOLCANO', 'RIFLE', 'BOIL',
        'HAIR', 'BICYCLE', 'JUMPER', 'SMOOTHIE', 'SLEEP',
        'PENTAGON', 'GROOM', 'RIVER', 'FARM', 'JUDGE',
        'VIKING', 'EASTER', 'MUD', 'PARROT', 'COMB',
        'SALSA', 'EDEN', 'ARMY', 'PADDLE', 'SALOON',
        'MONA LISA', 'MILE', 'BLIZZARD', 'QUARTER', 'JEWELER',
        'HAMBURGER', 'GLASSES', 'SAIL', 'BOXER', 'RICE',
        'MIRROR', 'INK', 'BEER', 'TIPI', 'MAKEUP',
        'MICROWAVE', 'HERCULES', 'SIGN', 'PIZZA', 'WOOL',
        'HOMER', 'MINUTE', 'SWORD', 'SOUP', 'ALASKA',
        'BABY', 'POTTER', 'SHOWER', 'BLADE', 'NOAH',
        'SOAP', 'TUNNEL', 'PEACH', 'DOLLAR', 'TIP',
        'LOVE', 'JELLYFISH', 'STETHOSCOPE', 'TASTE', 'FUEL',
        'MOSQUITO', 'WIZARD', 'BIG BEN', 'GARDEN', 'WAITRESS',
        'SHOOT', 'SHELL', 'LUMBERJACK', 'MEDIC', 'DREAM',
        'BLUES', 'EARTHQUAKE', 'PEA', 'PARADE', 'SLED',
        'SMELL', 'COMPUTER', 'COW', 'PEANUT', 'WINDOW',
        'MUSTARD', 'SAND', 'GOLF', 'CROW', 'ICELAND',
        'APRON', 'VIOLET', 'DOOR', 'TIGER', 'JOKER',
        'HOUSE', 'COLLAR', 'HAWAII', 'DWARF', 'PINE',
        'MAGICIAN', 'FROST', 'CURRY', 'BUBBLE', 'WOOD'
    ];
    private deepUndercover = [
        'ACID', 'ALCOHOL', 'ANIMAL', 'APPLES', 'ASHES',
        'ASS', 'BACON', 'BAKED', 'BALLOON', 'BALLS',
        'BANANAS', 'BANG', 'BAR', 'BARTENDER', 'BEACH',
        'BEANS', 'BEAR', 'BEAVER', 'BED', 'BEEF',
        'BEER', 'BEHIND', 'BENDER', 'BISCUITS', 'BISEXUAL',
        'BITCH', 'BLACK', 'BLING', 'BLONDE', 'BLOW',
        'BLUSH', 'BODY', 'BOND', 'BONDAGE', 'BONE',
        'BONG', 'BOOB', 'BOOTY', 'BOOZE', 'BOTTLE',
        'BOTTOM', 'BOWL', 'BOX', 'BOXERS', 'BOY',
        'BRA', 'BREAST', 'BRIEFS', 'BROWN', 'BROWNIE',
        'BURN', 'BUSH', 'BUST', 'BUTT', 'CABOOSE',
        'CANDLE', 'CANNONS', 'CARPET', 'CATCHER', 'CHAINS',
        'CHAMPAGNE', 'CHAPS', 'CHEEK', 'CHERRY', 'CHEST',
        'CHICK', 'CHOKE', 'CHUBBY', 'CIGAR', 'CIGARETTE',
        'CLAM', 'CLAP', 'CLUB', 'COCK', 'COCKTAIL',
        'COMMANDO', 'CONDOM', 'COOZIE', 'COUCH', 'COUGAR',
        'COUPLE', 'COWGIRL', 'COYOTE', 'CRABS', 'CRACK',
        'CRAP', 'CREAM', 'CUCUMBER', 'CUDDLE', 'CUFF',
        'DADDY', 'DAME', 'DIARRHEA', 'DICK', 'DILDO',
        'DOGGY', 'DOMINATE', 'DONKEY', 'DOUCHE', 'DOWN',
        'DRAG', 'DRILL', 'DRUNK', 'EAT', 'EMISSION',
        'ESCORT', 'EXPERIMENT', 'EYES', 'FACIAL', 'FANTASY',
        'FATTY', 'FEATHER', 'FECAL', 'FETISH', 'FILM',
        'FINGER', 'FIRE', 'FISH', 'FIST', 'FLASH',
        'FLESH', 'FLOWER', 'FLUFF', 'FORESKIN', 'FREAK',
        'FRECKLES', 'FRENCH', 'FRICTION', 'FURRY', 'G-SPOT',
        'GAG', 'GANG', 'GANGBANG', 'GASH', 'GAY',
        'GERBIL', 'GIGOLO', 'GIRL', 'GOOSE', 'GRANDMA',
        'GRASS', 'GROPE', 'GROUP', 'HAMMER', 'HAMSTER',
        'HAND', 'HEAD', 'HEADBOARD', 'HEADLIGHTS', 'HELL',
        'HERB', 'HIGH', 'HOLE', 'HOMERUN', 'HOOKER',
        'HOOTERS', 'HOOTERS', 'HORNY', 'HORSE', 'HOT',
        'HOTEL', 'HUMP', 'HURL', 'ICE', 'INCH',
        'INTERN', 'JAZZ', 'JERK', 'JEWELS', 'JOB',
        'JOHN', 'JOHNSON', 'JOINT', 'JOYSTICK', 'JUGS',
        'JUICE', 'KEG', 'KINKY', 'KITTY', 'KNEES',
        'KNOB', 'KNOCKERS', 'LATEX', 'LEGEND', 'LEGS',
        'LICK', 'LIGHTER', 'LINE', 'LINGERIE', 'LIPS',
        'LIQUOR', 'LIZARD', 'LOBSTER', 'LOG', 'LOOSE',
        'LOTION', 'LOVE', 'LUBE', 'LUST', 'MANBOOBS',
        'MARTINI', 'MATTRESS', 'MEAT', 'MELONS', 'MEMBER',
        'MESH', 'MILK', 'MISSIONARY', 'MIXER', 'MOIST',
        'MOLE', 'MOM', 'MONKEY', 'MOTEL', 'MOTORBOAT',
        'MOUTH', 'MOVIE', 'MUG', 'MUSHROOM', 'NAIL',
        'NAKED', 'NAVEL', 'NECKLACE', 'NEEDLE', 'NIPPLE',
        'NOODLE', 'NUDE', 'NURSE', 'NUTS', 'NYLON',
        'OLIVE', 'ONION', 'ORGASM', 'ORGY', 'OYSTER',
        'PACKAGE', 'PADDLE', 'PEACHES', 'PECKER', 'PEE',
        'PENIS', 'PERIOD', 'PICKLE', 'PIE', 'PIG',
        'PILLOWS', 'PIMP', 'PINCH', 'PINK', 'PIPE',
        'PITCHER', 'PLAYER', 'POKER', 'POLE', 'POOP',
        'PORK', 'PORN', 'POUND', 'PRICK', 'PRISON',
        'PROSTATE', 'PUB', 'PUCKER', 'PURPLE', 'PUSSY',
        'QUEEF', 'QUEEN', 'QUEER', 'RACK', 'RAVE',
        'RECTUM', 'RED', 'REGRET', 'ROACH', 'ROLL',
        'ROOF', 'ROOKIE', 'RUBBER', 'RUG', 'SACK',
        'SAFE', 'SALAD', 'SAUNA', 'SAUSAGE', 'SCORE',
        'SCREW', 'SEAT', 'SECRETARY', 'SEED', 'SEMEN',
        'SEX', 'SHAFT', 'SHAME', 'SHARE', 'SHAVE',
        'SHEEP', 'SHOT', 'SHOWER', 'SIN', 'SKANK',
        'SKID', 'SKIRT', 'SLUT', 'SMEGMA', 'SMELL',
        'SMOKE', 'SNAKE', 'SNATCH', 'SNIFF', 'SNORT',
        'SOFT', 'SOFTBALLS', 'SOLO', 'SORE', 'SPANK',
        'SPEED', 'SPERM', 'SPOON', 'SPREAD', 'SQUIRT',
        'STALKER', 'STEAMY', 'STIFF', 'STILETTO', 'STONES',
        'STOOL', 'STRAIGHT', 'STRAP', 'STRIP', 'STRIPPER',
        'STROBE', 'STUD', 'SWALLOW', 'SWIMMERS', 'TABOO',
        'TACO', 'TAIL', 'TAP', 'TAVERN', 'TEABAG',
        'TEASE', 'TENT', 'TEQUILA', 'THREESOME', 'THROAT',
        'TICKLE', 'TIE', 'TIP', 'TIT', 'TONGUE',
        'TOOL', 'TOP', 'TORTURE', 'TOUCH', 'TOUCHDOWN',
        'TOY', 'TRAIN', 'TRAMP', 'TRIM', 'TROUSERS',
        'TRUNK', 'TUBESTEAK', 'TUNA', 'TURD', 'TWIG',
        'UDDERS', 'URANUS', 'VASECTOMY', 'VEGAS', 'VEIN',
        'VIBRATOR', 'VIDEO', 'VINYL', 'VIRGIN', 'VODKA',
        'VOMIT', 'WAD', 'WANG', 'WASTE', 'WATCH',
        'WAX', 'WEED', 'WENCH', 'WET', 'WHIP',
        'WHISKEY', 'WHITE', 'WIENER', 'WINE', 'WOOD'
    ];

    private emojis = [
        '1f004', '1f0cf', '1f301', '1f302', '1f303', '1f304', '1f305', '1f306',
        '1f307', '1f308', '1f309', '1f30a', '1f30b', '1f30c', '1f30d', '1f30e',
        '1f30f', '1f311', '1f315', '1f319', '1f31a', '1f31b', '1f31c', '1f31d',
        '1f31e', '1f31f', '1f320', '1f321', '1f327', '1f328', '1f329', '1f32a',
        '1f32b', '1f32c', '1f32d', '1f32e', '1f32f', '1f330', '1f331', '1f332',
        '1f333', '1f334', '1f335', '1f336', '1f337', '1f338', '1f339', '1f33a',
        '1f33b', '1f33c', '1f33d', '1f33e', '1f33f', '1f340', '1f341', '1f342',
        '1f343', '1f344', '1f345', '1f346', '1f347', '1f348', '1f349', '1f34a',
        '1f34b', '1f34c', '1f34d', '1f34e', '1f34f', '1f350', '1f351', '1f352',
        '1f353', '1f354', '1f355', '1f356', '1f357', '1f358', '1f359', '1f35a',
        '1f35b', '1f35c', '1f35d', '1f35e', '1f35f', '1f360', '1f361', '1f362',
        '1f363', '1f364', '1f365', '1f366', '1f367', '1f368', '1f369', '1f36a',
        '1f36b', '1f36c', '1f36d', '1f36e', '1f36f', '1f370', '1f371', '1f372',
        '1f373', '1f374', '1f375', '1f376', '1f377', '1f378', '1f379', '1f37a',
        '1f37b', '1f37c', '1f37d', '1f37e', '1f37f', '1f380', '1f381', '1f382',
        '1f383', '1f384', '1f385', '1f386', '1f387', '1f388', '1f389', '1f38a',
        '1f38b', '1f38c', '1f38d', '1f38e', '1f38f', '1f390', '1f391', '1f392',
        '1f393', '1f396', '1f397', '1f399', '1f39a', '1f39b', '1f39e', '1f39f',
        '1f3a0', '1f3a1', '1f3a2', '1f3a3', '1f3a4', '1f3a5', '1f3a7', '1f3a8',
        '1f3a9', '1f3aa', '1f3ab', '1f3ac', '1f3ad', '1f3ae', '1f3af', '1f3b0',
        '1f3b1', '1f3b2', '1f3b3', '1f3b4', '1f3b5', '1f3b6', '1f3b7', '1f3b8',
        '1f3b9', '1f3ba', '1f3bb', '1f3bc', '1f3bd', '1f3be', '1f3bf', '1f3c0',
        '1f3c1', '1f3c2', '1f3c3', '1f3c4', '1f3c5', '1f3c6', '1f3c7', '1f3c8',
        '1f3c9', '1f3ca', '1f3cb', '1f3cc', '1f3cd', '1f3ce', '1f3cf', '1f3d0',
        '1f3d1', '1f3d2', '1f3d3', '1f3d4', '1f3d5', '1f3d6', '1f3d7', '1f3d8',
        '1f3d9', '1f3da', '1f3db', '1f3dc', '1f3dd', '1f3de', '1f3df', '1f3e0',
        '1f3e1', '1f3e2', '1f3e3', '1f3e4', '1f3e5', '1f3e6', '1f3e7', '1f3e8',
        '1f3e9', '1f3eb', '1f3ec', '1f3ed', '1f3ee', '1f3ef', '1f3f0', '1f3f3',
        '1f3f4', '1f3f5', '1f3f7', '1f3f8', '1f3f9', '1f3fa', '1f400', '1f401',
        '1f402', '1f403', '1f404', '1f405', '1f406', '1f407', '1f408', '1f409',
        '1f40a', '1f40b', '1f40c', '1f40d', '1f40e', '1f40f', '1f410', '1f411',
        '1f412', '1f413', '1f414', '1f415', '1f416', '1f417', '1f418', '1f419',
        '1f41a', '1f41b', '1f41c', '1f41d', '1f41e', '1f41f', '1f420', '1f421',
        '1f422', '1f423', '1f424', '1f425', '1f426', '1f427', '1f428', '1f429',
        '1f42a', '1f42b', '1f42c', '1f42d', '1f42e', '1f42f', '1f430', '1f431',
        '1f432', '1f433', '1f434', '1f435', '1f436', '1f437', '1f438', '1f439',
        '1f43a', '1f43b', '1f43c', '1f43d', '1f43e', '1f43f', '1f440', '1f441',
        '1f442', '1f443', '1f444', '1f445', '1f446', '1f447', '1f448', '1f449',
        '1f44a', '1f44b', '1f44c', '1f44d', '1f44e', '1f44f', '1f450', '1f451',
        '1f452', '1f453', '1f454', '1f455', '1f456', '1f457', '1f458', '1f459',
        '1f45a', '1f45b', '1f45c', '1f45d', '1f45e', '1f45f', '1f460', '1f461',
        '1f462', '1f463', '1f46a', '1f46b', '1f46c', '1f46d', '1f46e', '1f46f',
        '1f470', '1f471', '1f472', '1f473', '1f474', '1f475', '1f476', '1f477',
        '1f478', '1f479', '1f47a', '1f47b', '1f47c', '1f47d', '1f47e', '1f47f',
        '1f480', '1f481', '1f482', '1f483', '1f484', '1f485', '1f486', '1f487',
        '1f488', '1f489', '1f48a', '1f48b', '1f48c', '1f48d', '1f48e', '1f48f',
        '1f490', '1f491', '1f492', '1f493', '1f494', '1f495', '1f496', '1f497',
        '1f498', '1f499', '1f49a', '1f49b', '1f49c', '1f49d', '1f49e', '1f49f',
        '1f4a0', '1f4a1', '1f4a2', '1f4a3', '1f4a4', '1f4a5', '1f4a6', '1f4a7',
        '1f4a8', '1f4a9', '1f4aa', '1f4ab', '1f4ac', '1f4ad', '1f4ae', '1f4af',
        '1f4b0', '1f4b3', '1f4b4', '1f4b5', '1f4b6', '1f4b7', '1f4b8', '1f4b9',
        '1f4ba', '1f4bb', '1f4bc', '1f4bd', '1f4be', '1f4bf', '1f4c0', '1f4c1',
        '1f4c4', '1f4c5', '1f4c7', '1f4c8', '1f4c9', '1f4ca', '1f4cb', '1f4cc',
        '1f4cd', '1f4ce', '1f4cf', '1f4d0', '1f4d1', '1f4d2', '1f4d8', '1f4da',
        '1f4db', '1f4dc', '1f4dd', '1f4de', '1f4df', '1f4e0', '1f4e1', '1f4e2',
        '1f4e6', '1f4e8', '1f4ec', '1f4ef', '1f4f0', '1f4f7', '1f4f8', '1f4f9',
        '1f4fa', '1f4fb', '1f4fc', '1f4fd', '1f4ff', '1f509', '1f50a', '1f50b',
        '1f50c', '1f50d', '1f510', '1f511', '1f512', '1f513', '1f514', '1f515',
        '1f516', '1f517', '1f51e', '1f525', '1f526', '1f527', '1f528', '1f529',
        '1f52a', '1f52b', '1f52c', '1f52d', '1f52e', '1f54a', '1f54b', '1f54c',
        '1f54d', '1f54e', '1f56f', '1f570', '1f573', '1f574', '1f575', '1f576',
        '1f577', '1f578', '1f579', '1f57a', '1f587', '1f58a', '1f58d', '1f590',
        '1f595', '1f596', '1f5a4', '1f5a5', '1f5a8', '1f5b1', '1f5b2', '1f5bc',
        '1f5c2', '1f5c3', '1f5c4', '1f5d1', '1f5d2', '1f5d3', '1f5dc', '1f5dd',
        '1f5de', '1f5e1', '1f5e3', '1f5e8', '1f5ef', '1f5f3', '1f5fa', '1f5fb',
        '1f5fc', '1f5fd', '1f5fe', '1f5ff', '1f600', '1f601', '1f602', '1f603',
        '1f604', '1f605', '1f606', '1f607', '1f608', '1f609', '1f60a', '1f60b',
        '1f60c', '1f60d', '1f60e', '1f60f', '1f610', '1f611', '1f612', '1f613',
        '1f614', '1f615', '1f616', '1f617', '1f618', '1f619', '1f61a', '1f61b',
        '1f61c', '1f61d', '1f61e', '1f61f', '1f620', '1f621', '1f622', '1f623',
        '1f624', '1f625', '1f626', '1f627', '1f628', '1f629', '1f62a', '1f62b',
        '1f62c', '1f62d', '1f62e', '1f62f', '1f630', '1f631', '1f632', '1f633',
        '1f634', '1f635', '1f636', '1f637', '1f638', '1f639', '1f63a', '1f63b',
        '1f63c', '1f63d', '1f63e', '1f63f', '1f640', '1f641', '1f642', '1f643',
        '1f644', '1f645', '1f646', '1f647', '1f648', '1f649', '1f64a', '1f64b',
        '1f64c', '1f64d', '1f64e', '1f64f', '1f680', '1f681', '1f682', '1f683',
        '1f684', '1f685', '1f686', '1f687', '1f688', '1f689', '1f68a', '1f68b',
        '1f68c', '1f68d', '1f68e', '1f68f', '1f690', '1f691', '1f692', '1f693',
        '1f694', '1f695', '1f696', '1f697', '1f698', '1f699', '1f69a', '1f69b',
        '1f69c', '1f69d', '1f69e', '1f69f', '1f6a0', '1f6a1', '1f6a2', '1f6a3',
        '1f6a4', '1f6a5', '1f6a6', '1f6a7', '1f6a8', '1f6a9', '1f6aa', '1f6ab',
        '1f6ac', '1f6b2', '1f6b4', '1f6b6', '1f6bd', '1f6bf', '1f6c1', '1f6cb',
        '1f6cc', '1f6cd', '1f6ce', '1f6cf', '1f6d1', '1f6d2', '1f6d5', '1f6d6',
        '1f6e0', '1f6e1', '1f6e2', '1f6e3', '1f6e4', '1f6e5', '1f6e9', '1f6eb',
        '1f6ec', '1f6f0', '1f6f3', '1f6f4', '1f6f5', '1f6f6', '1f6f7', '1f6f8',
        '1f6f9', '1f6fa', '1f6fb', '1f6fc', '1f90c', '1f90d', '1f90e', '1f90f',
        '1f910', '1f911', '1f912', '1f913', '1f914', '1f915', '1f916', '1f917',
        '1f918', '1f919', '1f91a', '1f91b', '1f91c', '1f91d', '1f91e', '1f91f',
        '1f920', '1f921', '1f922', '1f923', '1f924', '1f925', '1f926', '1f927',
        '1f928', '1f929', '1f92a', '1f92b', '1f92c', '1f92d', '1f92e', '1f92f',
        '1f930', '1f931', '1f932', '1f933', '1f934', '1f935', '1f936', '1f937',
        '1f938', '1f939', '1f93a', '1f93c', '1f93d', '1f93e', '1f93f', '1f940',
        '1f941', '1f942', '1f943', '1f944', '1f945', '1f947', '1f948', '1f949',
        '1f94a', '1f94b', '1f94c', '1f94d', '1f94e', '1f94f', '1f950', '1f951',
        '1f952', '1f953', '1f954', '1f955', '1f956', '1f957', '1f958', '1f959',
        '1f95a', '1f95b', '1f95c', '1f95d', '1f95e', '1f95f', '1f960', '1f961',
        '1f962', '1f963', '1f964', '1f965', '1f966', '1f967', '1f968', '1f969',
        '1f96a', '1f96b', '1f96c', '1f96d', '1f96e', '1f96f', '1f970', '1f971',
        '1f972', '1f973', '1f974', '1f975', '1f976', '1f977', '1f978', '1f97a',
        '1f97b', '1f97c', '1f97d', '1f97e', '1f97f', '1f980', '1f981', '1f982',
        '1f983', '1f984', '1f985', '1f986', '1f987', '1f988', '1f989', '1f98a',
        '1f98b', '1f98c', '1f98d', '1f98e', '1f98f', '1f990', '1f991', '1f992',
        '1f993', '1f994', '1f995', '1f996', '1f997', '1f998', '1f999', '1f99a',
        '1f99b', '1f99c', '1f99d', '1f99e', '1f99f', '1f9a0', '1f9a1', '1f9a2',
        '1f9a3', '1f9a4', '1f9a5', '1f9a6', '1f9a7', '1f9a8', '1f9a9', '1f9aa',
        '1f9ab', '1f9ac', '1f9ad', '1f9ae', '1f9af', '1f9b4', '1f9b5', '1f9b6',
        '1f9b7', '1f9b8', '1f9b9', '1f9ba', '1f9bb', '1f9bd', '1f9be', '1f9bf',
        '1f9c0', '1f9c1', '1f9c2', '1f9c3', '1f9c4', '1f9c5', '1f9c6', '1f9c7',
        '1f9c8', '1f9c9', '1f9ca', '1f9cb', '1f9cd', '1f9ce', '1f9cf', '1f9d0',
        '1f9d4', '1f9d5', '1f9d6', '1f9d7', '1f9d8', '1f9d9', '1f9da', '1f9db',
        '1f9dc', '1f9dd', '1f9de', '1f9df', '1f9e0', '1f9e1', '1f9e2', '1f9e3',
        '1f9e4', '1f9e5', '1f9e6', '1f9e7', '1f9e8', '1f9e9', '1f9ea', '1f9eb',
        '1f9ec', '1f9ed', '1f9ee', '1f9ef', '1f9f0', '1f9f1', '1f9f2', '1f9f3',
        '1f9f4', '1f9f5', '1f9f6', '1f9f7', '1f9f8', '1f9f9', '1f9fa', '1f9fb',
        '1f9fc', '1f9fd', '1f9fe', '1fa70', '1fa71', '1fa72', '1fa73', '1fa74',
        '1fa78', '1fa79', '1fa7a', '1fa80', '1fa81', '1fa82', '1fa83', '1fa84',
        '1fa85', '1fa86', '1fa90', '1fa91', '1fa92', '1fa93', '1fa94', '1fa95',
        '1fa96', '1fa97', '1fa98', '1fa99', '1fa9a', '1fa9b', '1fa9c', '1fa9d',
        '1fa9e', '1fa9f', '1faa0', '1faa1', '1faa2', '1faa3', '1faa4', '1faa5',
        '1faa6', '1faa7', '1faa8', '1fab0', '1fab1', '1fab2', '1fab3', '1fab4',
        '1fab5', '1fab6', '1fac0', '1fac1', '1fac2', '1fad0', '1fad1', '1fad2',
        '1fad3', '1fad4', '1fad5', '1fad6', '231a', '231b', '2328', '23f0',
        '23f1', '23f2', '23f3', '2600', '2601', '2602', '2603', '2604',
        '260e', '2611', '2614', '2615', '2618', '261d', '2620', '2622',
        '2623', '262a', '262e', '262f', '2639', '263a', '2640', '2642',
        '265f', '2660', '2663', '2665', '2666', '2668', '267b', '2692',
        '2693', '2694', '2695', '2696', '2697', '2699', '269c', '26a0',
        '26a1', '26b0', '26b1', '26bd', '26be', '26c4', '26c5', '26c8',
        '26ce', '26cf', '26d1', '26d3', '26d4', '26e9', '26ea', '26f0',
        '26f1', '26f2', '26f3', '26f4', '26f5', '26f7', '26f8', '26f9',
        '26fa', '26fd', '2702', '2705', '2708', '2709', '270a', '270b',
        '270c', '270d', '270f', '2712', '2714', '2716', '2721', '2728',
        '2744', '2763', '2764', '2b50',
    ];
    private tvWords = [
        'SEINFELD', 'THE WEST WING', 'REAL HOUSEWIVES', 'M*A*S*H', 'JUDGE JUDY', 'THE SIMPSONS', 'JEOPARDY', 'GENERAL HOSPITAL',
        'THE FRESH PRINCE OF BEL-AIR', 'GAME OF THRONES', 'KEEPING UP WITH THE KARDASHIANS', 'MR. ED', 'THE TONIGHT SHOW', 'RICK AND MORTY', 'WHEEL OF FORTUNE', 'THE DAYS OF OUR LIVES',
        'FRASIER', 'THE WIRE', 'THE GREAT BRITISH BAKING SHOW', 'THE DICK VAN DYKE SHOW', 'THE COLBERT REPORT', 'FUTURAMA', 'FAMILY FEUD', 'AS THE WORLD TURNS',
        'FRIENDS', 'MAD MEN', 'THE AMAZING RACE', 'I LOVE LUCY', 'SESAME STREET', 'SOUTH PARK', 'THE PRICE IS RIGHT', 'ALL MY CHILDREN',
        'SATURDAY NIGHT LIVE', 'THE SOPRANOS', 'TOP CHEF', 'ALL IN THE FAMILY', 'READING RAINBOW', 'BEAVIS AND BUTT-HEAD', 'AMERICAN GLADIATORS',
        'MARRIED WITH CHILDREN', 'BREAKING BAD', 'SURVIVOR', 'MONTY PYTHONS FLYING CIRCUS', 'LAST WEEK TONIGHT', 'FAMILY GUY', 'AMERICAN NINJA WARRIOR',
        'MODERN FAMILY', 'THE TWILIGHT ZONE', 'PROJECT RUNWAY', 'COLUMBO', 'MR. ROGERS NEIGHBORHOOD', 'INSPECTOR GADGET', 'DEAL OR NO DEAL',
        'THE DAILY SHOW', 'STAR TREK', 'THE BACHELOR', 'MURDER, SHE WROTE', 'THE ED SULLIVAN SHOW', 'THE SMURFS', 'DOUBLE DARE',
        'CHEERS', 'STAR TREK THE NEXT GENERATION', 'AMERICAS NEXT TOP MODEL', 'TAXI', 'THUNDERCATS', 'LETS MAKE A DEAL',
        'CURB YOUR ENTHUSIASM', 'FRIDAY NIGHT LIGHTS', 'SHARK TANK', 'HAPPY DAYS', 'VOLTRON', 'SUPERMARKET SWEEP',
        'THE OFFICE', 'THE X-FILES', 'THE REAL WORLD', 'THE JEFFERSONS', 'ANIMANIACS', 'THE NEWLYWED GAME',
        'PARKS AND RECREATION', 'LAW AND ORDER', 'AMERICAN IDOL', 'GOOD TIMES', 'AVATAR: THE LAST AIRBENDER', 'TEN THOUSAND DOLLAR PYRAMID',
        'VEEP', 'ER', 'THE VOICE', 'THE GOLDEN GIRLS', 'SCOOBY DOO',
        'ARRESTED DEVELOPMENT', 'GREYS ANATOMY', 'THE MASKED SINGER', 'HILL STREET BLUES', 'SPONGEBOB SQUAREPANTS',
        '30 ROCK', 'BUFFY THE VAMPIRE SLAYER', 'DANCING WITH THE STARS', 'THE MARY TYLER MOORE SHOW', 'KING OF THE HILL',
        'ORANGE IS THE NEW BLACK', 'LOST', 'TOP GEAR', 'GET SMART', 'AQUA TEEN HUNGER FORCE',
        'ITS ALWAYS SUNNY IN PHILADELPHIA', 'NYPD BLUE', 'RUPAULS DRAG RACE', 'THE POWERPUFF GIRLS',
        'TED LASSO', 'THE AMERICANS', 'THE CHALLENGE', 'THE TRANSFORMERS',
        'THE MUPPET SHOW', 'SEX AND THE CITY', 'WHOSE LINE IS IT ANYWAY', 'THE JETSONS',
        'ROSEANNE / THE CONNERS', 'THE WONDER YEARS', 'FEAR FACTOR', 'CAPTAIN UNDERPANTS',
        'CHAPELLES SHOW', 'DOWNTON ABBEY', 'BIG BROTHER', 'ARCHER',
        'IN LIVING COLOR', 'GIRLS', 'IRON CHEF',
        'THE DREW CAREY SHOW', 'THE WALKING DEAD', 'THE BIGGEST LOSER',
        'WEEDS', 'DOCTOR WHO',
        'BLACKISH', 'HOMELAND',
        'THE BIG BANG THEORY', 'BAND OF BROTHERS',
        'THE GOOD PLACE', 'TRUE DETECTIVE',
        'COMMUNITY', '24',
        'COMEDIANS IN CARS GETTING COFFEE', 'DEXTER',
        'BROOKLYN NINE-NINE', 'FIREFLY',
        'SILICON VALLEY', 'CSI: CRIME SCENE INVESTIGATION',
        'SCHITTS CREEK', 'HOUSE',
        'FLEABAG', 'DESPERATE HOUSEWIVES',
        'THE MARVELOUS MRS. MASEL', 'GILMORE GIRLS',
        'EVERYBODY LOVES RAYMOND', 'MONK',
        'WILL AND GRACE', 'VERONICA MARS',
        'MURPHY BROWN', 'MR. ROBOT',
        '3RD ROCK FROM THE SUN', 'SHERLOCK',
        'THE COSBY SHOW', 'BETTER CALL SAUL',
        'SAVED BY THE BELL', 'THE MANDALORIAN',
        'THE FACTS OF LIFE', 'SUCCESSION',
        'WHOS THE BOSS', 'THE HANDMAIDS TALE',
        'FAMILY TIES', 'THE PRACTICE',
        'ALF', 'THE NEWSROOM',
        'THE KIDS IN THE HALL', 'ATLANTA',
        'KEY AND PEELE', 'THE CROWN',
        'THE LEAGUE', 'KILLING EVE',
        'PORTLANDIA', 'THE A-TEAM',
        'NEWS RADIO', 'ANGEL',
        'HOW I MET YOUR MOTHER', 'MIGHTY MORPHIN POWER RANGERS',
        'THE STATE', 'LOUIE',
        'MYSTERY SCIENCE THEATER 3000', 'CALIFORNICATION',
        'SCRUBS', 'STAR TREK VOYAGER',
        'AMERICAS FUNNIEST HOME VIDEOS', 'STAR TREK DEEP SPACE NINE',
        'THE NANNY', 'PSYCH',
        'MYTHIC QUEST', 'WANDAVISION',
        'THE RED GREEN SHOW', 'LOKI',
        'THE BRADY BUNCH',
        'THAT 70S SHOW',
    ];
    private popCultureWords = [
        'TOM HANKS', 'MICHAEL JACKSON', 'PABLO PICASSO', 'ALEX TREBEK', 'CHARLES DE GAUL', 'LARRY BIRD', 'MICHAEL JORDAN', 'TOM BRADY',
        'MERYL STREEP', 'MADONNA', 'GEORGIA OKEEFFE', 'VANNA WHITE', 'SALLY RIDE', 'FLORENCE GRIFFITH-JOYNER', 'DIANA TSAURASI', 'SUE BIRD',
        'GEORGE CLOONEY', 'PAUL MCCARTNEY', 'BANKSY', 'KYLIE JENNER', 'ALEXANDER THE GREAT', 'EARVIN MAGIC JOHNSON', 'MICHAEL PHELPS', 'AARON RODGERS',
        'JENNIFER ANISTON', 'CHER', 'FRIDA KAHLO', 'ELLEN DEGENERES', 'CLEOPATRA', 'MARY LOU RETTON', 'KRISTI YAMAGUCHI', 'MEGAN RAPINOE',
        'MATT DAMON', 'JIMI HENDRIX', 'ANDY WARHOL', 'BILL GATES', 'MOHANDAS GHANDI', 'JOE MONTANA', 'TONY HAWK', 'USAIN BOLT',
        'GLENN CLOSE', 'LADY GAGA', 'J.K. ROWLING', 'OPRAH WINFREY', 'JULIA CHILD', 'JACKIE JOYNER-KERSEE', 'BONNIE BLAIR', 'SIMONE BILES',
        'DON CHEADLE', 'KURT COBAIN', 'VINCENT VAN GOGH', 'JEFF BEZOS', 'MONTEZUMA', 'MIKE TYSON', 'PEDRO MARTINEZ', 'LEBRON JAMES',
        'KATE WINSLET', 'CARDI B', 'AGATHA CHRISTIE', 'JUDGE JUDY', 'BARBARA WALTERS', 'BILLIE JEAN KING', 'MICHELLE KWAN', 'KATIE LEDECKY',
        'BRAD PITT', 'DR. DRE', 'LEONARDO DA VINCI', 'STEVE BALMER', 'PETER THE GREAT', 'WAYNE GRETZKY', 'KOBE BRYANT', 'SHAUN WHITE',
        'VIOLA DAVIS', 'NICKI MINAJ', 'LAURA INGALLS WILDER', 'KIM KARSASHIAN', 'HARRIET TUBMAN', 'NADIA COMANICI', 'VENUS WILLIAMS', 'LINDSEY VONN',
        'JERRY SEINFELD', 'SNOOP DOGG', 'MICHAELANGELO', 'LINUS TORVALDS', 'HAMMURABI', 'BILL RUSSELL', 'DAVID BECKHAM', 'BODE MILLER',
        'JULIA LOUIS-DREYFUSS', 'MARIAH CAREY', 'CAROL BURNETT', 'ANNA-NICOLE SMITH', 'JANE GOODALL', 'STEFFI GRAF', 'SERENA WILLIAMS',
        'LEONARDO DICAPRIO', 'TUPAC SHAKUR', 'CLAUDE MONET', 'STEVEN SPIELBERG', 'HENRY VIII', 'WILT CHAMBERLAIN', 'TIGER WOODS', 'CHRISTIANO RONALDO',
        'NICOLE KIDMAN', 'GWEN STEFANI', 'GILDA RADNER', 'GILDA RADNER', 'MARIE ANTIONETTE', 'HOPE SOLO', 'RONDA ROUSEY',
        'CHADWICK BOSEMAN', 'BUDDY HOLLY', 'REMBRANDT', 'STEVE JOBS', 'GENGIS KHAN', 'JESSE OWENS', 'BARRY BONDS', 'LEO MESSI',
        'JENNIFER LAWRENCE', 'KATY PERRY', 'ALI WONG', 'ELANOR ROOSEVELT', 'LISA LESLIE', 'ALEX MORGAN',
        'KEANU REEVES', 'BLAKE SHELTON', 'SALVADOR DALI', 'MARK ZUCKERBERG', 'JULIUS CAESAR', 'MUHAMMAD ALI', 'MARK MCGWIRE',
        'EMMA STONE', 'TAYLOR SWIFT', 'DIANE SAWYER', 'SUSAN B. ANTHONY', 'ABBY WAMBACH', 'MARTA',
        'LAWRENCE FISHBURNE', 'JAY-Z', 'FRANK LLOYD WRIGHT', 'JIMMY KIMMEL', 'LENIN', 'MICKEY MANTLE', 'SAMMY SOSA',
        'RENEE ZELLWEGER', 'BEYONCE', 'CHELSEA LATELY', 'POCHAHONTAS', 'MIA HAMM', 'MARIA SHARAPOVA',
        'LARRY DAVID', 'JUSTIN BEIBER', 'JIM HENSON', 'JAY LENO', 'NAPOLEON BONAPARTE', 'GEORGE FOREMAN', 'BILL BELICHIK',
        'SANDRA BULLOCK', 'DIANA ROSS', 'ELLEN DEGENERES', 'AMELIA EARHART', 'ANNIKA SORENSTAM',
        'GEORGE CARLIN', 'BILLY JOEL', 'DAVID LETTERMAN', 'NEIL ARMSTRONG', 'PELE',
        'MARILYN MONROE', 'ARETHA FRANKLIN', 'MARIE CURIE', 'KERRI STRUG',
        'ROBERT DENIRO', 'ELTON JOHN', 'STEPHEN COLBERT', 'YURI GAGARIN', 'JACK NICKALUS',
        'AUDREY HEPBURN', 'BILLIE HOLIDAY', 'CONAN OBRIEN', 'HELEN KELLER',
        'CLINT EASTWOOD', 'THE WEEKND', 'MAO ZEDONG', 'ARNOLD PALMER',
        'JULIE ANDREWS', 'ELLA FITZGERALD', 'JERRY SPRINGER', 'ROSA PARKS',
        'DANNY DEVITO', 'MICK JAGGER', 'ALBERT EINSTEIN', 'JACKIE ROBINSON',
        'CATE BLANCHETT', 'WHITNEY HOUSTON', 'DAVE CHAPPELLE', 'CATHERINE DE MEDICI',
        'MORGAN FREEMAN', 'SAMMY DAVIS JR.', 'CHRISTOPHER COLOMBUS',
        'LUCILLE BALL', 'LAURYN HILL', 'JOAN OF ARC',
        'CHARLIE CHAPLIN', 'FRANK SINATRA', 'JESUS OF NAZARINE',
        'JULIA ROBERTS', 'CHRISTINA AGUILERA', 'PRINCESS DIANA',
        'JACKIE CHAN', 'WOLFGANG AMADEUS MOZART', 'MUHAMMAD IBN ABDULLAH',
        'JODIE FOSTER', 'ADELE', 'ANNE FRANK',
        'WILL SMITH', 'JOHANN SEBASTIAN BACH', 'WINSTON CHURCHILL',
        'GWYNETH PALTROW', 'BRITNEY SPEARS', 'MOTHER THERESA',
        'BRUCE LEE', 'LUDWIG VAN BEETHOVEN', 'WILLIAM SHAKESPEARE',
        'UMA THURMAN', 'SARAH MACLACHLAN', 'SACAGAWEA',
        'TOM CRUISE', 'PYOTR ILYICH TCHAIKOVSKY', 'CHE GUEVARA',
        'WHOOPI GOLDBERG', 'BONNIE RAITT', 'ANN BOLEYN',
        'BENECIO DEL TORO', 'ELVIS PRESLEY', 'MARTIN LUTHER KING, JR.',
        'MILA KUNIS', 'BETTE MIDLER', 'CLARA BARTON',
        'MICHAEL DOUGLASS', 'LOUIS ARMSTRONG', 'CHARLES DARWIN',
        'SARAH MICHELLE GELLAR', 'RIHANNA', 'SOJOURNER TRUTH',
        'KIRK DOUGLASS', 'BOB MARLEY', 'STEPHEN HAWKING',
        'ELIZABETH TAYLOR', 'DOLLY PARTON', 'MALALA YOUSAFZAI',
        'JAMES DEAN', 'JUSTIN TIMBERLAKE', 'ISAAC NEWTON',
        'KATHERINE ZETA-JONES', 'AMY WINEHOUSE', 'ADA LOVELACE',
        'IDRIS ELBA', 'EMINEM', 'NELSON MANDELA',
        'MAYA RUDOLPH', 'SHAKIRA',
        'TED DANSON', 'BRUCE SPRINGSTEEN', 'GEORGE WASHINGTON CARVER',
        'TINA FEY', 'OLIVIA RODRIGO',
        'WILL FARRELL', 'BRIAN WILSON',
        'AMY POEHLER', 'KELLY CLARKSON',
        'ROBERT DOWNEY JR.', 'JOHN LEGEND',
        'WANDA SYKES', 'ARIANNA GRANDE',
        'CHRIS HEMSWORTH', 'FRANK ZAPPA',
        'TIFFANY HADDISH', 'GLADYS KNIGHT',
        'SAMUEL L. JACKSON', 'BOB DYLAN',
        'JOAN RIVERS', 'PINK',
        'JOHN TRAVOLTA', 'NOTORIOUS B.I.G.',
        'MINDY KALING', 'ANNIE LENNOX',
        'SEAN CONNERY', 'SEAN PUFFY COMBS',
        'MARGARET CHO', 'JANET JACKSON',
        'RALPH FIENNES', 'B.B. KING',
        'SCARLETT JOHANSSON', 'BILLIE EILISH',
        'CHRIS EVANS', 'JAMES BROWN',
        'KATE MCKINNON', 'CELINE DION',
        'LIL NAS X',
        'KIRSTEN WIIG',
        'PAUL SIMON',
    ];

    private thanksgiving = [
        'acorn',
        'America',
        'American',
        'apple',
        'apple pie',
        'ate',
        'autumn',
        'bake',
        'baste',
        'beans',
        'bread',
        'buns',
        'canoe',
        'carve',
        'casserole',
        'celebrate',
        'centerpiece',
        'Colonists',
        'cook',
        'corn',
        'cornbread',
        'cornucopia',
        'cranberries',
        'cranberry',
        'cranberry sauce',
        'delicious',
        'dessert',
        'dine',
        'dinner',
        'dish',
        'drumstick',
        'eat',
        'Fall',
        'family',
        'feast',
        'fish',
        'football',
        'friends',
        'giblets',
    'gobble',
        'grandparents',
        'grateful',
        'gratitude',
        'gravy',
        'ham',
        'harvest',
        'holiday',
        'home',
        'Indian',
        'Indian corn',
        'leaf',
        'leaves',
        'leftovers',
        'Massachusetts',
        'Massachusetts Bay Colony',
        'Massasoit',
        'Mayflower',
        'meal',
        'meat',
        'melting pot',
        'napkin',
        'native',
        'Native American',
        'New World',
        'November',
        'oven',
        'pans',
        'parents',
        'Patuxet Indians',
        'pecan',
        'pie',
        'Pilgrim',
        'platter',
        'Plymouth',
        'Plymouth Rock',
        'potato',
        'pots',
        'pumpkin',
        'pumpkin pie',
        'recipe',
        'roast',
        'rolls',
        'sail',
        'salad',
        'sauce',
        'serve',
        'settlers',
        'Squanto',
        'squash',
        'stuffing',
        'sweet corn',
        'sweet potato',
        'tablecloth',
        'taste',
        'tasty',
        'thankful',
        'Thanksgiving Day',
        'Thursday',
        'Tisquantum',
        'tom turkey',
        'tradition',
        'turkey',
        'vegetables',
        'voyage',
        'Wampanoag Indians',
        'wishbone',
        'yam',
    ];

    private christmas = ['Advent',
        'Angels',
        'Announcement',
        'Bells',
        'Bethlehem',
        'Blitzen',
        'Candles',
        'Candy',
        'Candy canes',
        'Cards',
        'Cedar',
        'Celebrate',
        'Ceremonies',
        'Chimney',
        'Christmas cookies',
        'Christmas tree',
        'Cold',
        'Comet',
        'Cranberry sauce',
        'Crowds',
        'Cupid',
        'Dancer',
        'Dasher',
        'December',
        'Decorations',
        'Dolls',
        'Donner',
        'Dressing',
        'Eggnog',
        'Elves',
        'Family reunion',
        'Festival',
        'Fir',
        'Frosty',
        'Fruitcake',
        'Gift boxes',
        'Gifts',
        'Goodwill',
        'Greetings',
        'Ham',
        'Happy',
        'Holiday',
        'Holly',
        'Holy',
        'Icicles',
        'Jolly',
        'Lights',
        'Lists',
        'Merry',
        'Miracle',
        'Mistletoe',
        'New Year',
        'Noel',
        'North Pole',
        'Pageant',
        'Parades',
        'Party',
        'Pie',
        'Pine',
        'Plum pudding',
        'Poinsettia',
        'Prancer',
        'Presents',
        'Pumpkin pie',
        'Punch',
        'Red/green',
        'Reindeer',
        'Ribbon',
        'Rudolph',
        'Sacred',
        'Sales',
        'Sauce',
        'Scrooge',
        'Season',
        'Sled',
        'Sleighbells',
        'Snowflakes',
        'Spirit',
        'St. Nick',
        'Stand',
        'Star',
        'Stickers',
        'Stocking stuffers',
        'Sweet potato',
        'Tidings',
        'Tinsel',
        'Togetherness',
        'Toys',
        'Tradition',
        'Traffic',
        'Trips',
        'Turkey',
        'Vacation',
        'Vixen',
        'Winter',
        'Worship',
        'Wrapping paper',
        'Wreath',
        'Yule',
        'Yuletide',
    ];

    private mlk = [
      'Abolition',
      'Armstrong',
      'Africa',
      'Ali',
      'Soul',
      'Blues',
      'Boycott',
      'Bus',
      'Carver',
      'Civil',
      'Rights',
      'War',
      'Voting',
      'Emancipation',
      'Equality',
      'Freedom',
      'Truth',
      'Integration',
      'Jazz',
      'Jim',
      'Crow',
      'March',
      'King',
      'Racism',
      'Slavery',
    ];

    private halloween = ['apparition',
      'enchanted',
      'ghost',
      'ghostly',
      'ghoulish',
      'goblin',
      'haunted house',
      'haunting',
      'hobgoblin',
      'levitation',
      'medium',
      'occult',
      'orbs',
      'paranormal',
      'phantasm',
      'phantom',
      'poltergeist',
      'possessed',
      'possession',
      'seance',
      'specter',
      'spirit',
      'unearthly',
      'wraith',
      'bloodcurdling',
      'bloodsucker',
      'bloody',
      'bones',
      'carved',
      'chainsaw',
      'decapitated',
      'demon',
      'evil',
      'exorcism',
      'fangs',
      'gory',
      'grim',
      'gruesome',
      'knife',
      'lurking',
      'macabre',
      'mummified',
      'pitchfork',
      'reanimated',
      'ritualistic',
      'satanic',
      'spine-chilling',
      'spine-tingling',
      'spree killer',
      'bat',
      'cadaver',
      'casket',
      'cemetery',
      'cobweb',
      'coffin',
      'corpse',
      'crematorium',
      'crypt',
      'cursed',
      'decomposing',
      'eerie',
      'epitaph',
      'full moon',
      'gravestone',
      'graveyard',
      'howling',
      'magic',
      'mausoleum',
      'morbid',
      'owl',
      'shadow',
      'skull',
      'spider',
      'tomb',
      'black cat',
      'black dress',
      'broomstick',
      'cackle',
      'cape',
      'cauldron',
      'conical hat',
      'crone',
      'eye of newt',
      'hag',
      'hex',
      'hocus pocus',
      'incantation',
      'magic',
      'magic potion',
      'necromancy',
      'pointy shoes',
      'sorcery',
      'spell',
      'superstition',
      'toad',
      'wand',
      'warlock',
      'Wiccan',
      'witchcraft',
      'boogeyman',
      'grim reaper',
      'living dead',
      'monsters',
      'mummy',
      'shadowy figure',
      'skeleton',
      'troll',
      'undead',
      'vampire',
      'werewolf',
      'wizard',
      'zombie',
      'candy',
      'costume party',
      'costumes',
      'dark',
      'devilish',
      'disguise',
      'face paint',
      'ghost story',
      'jack-o-lantern',
      'masks',
      'scary story',
      'treats',
      'trick or treat',
      'tricks',
      'trunk or treat',
    ];

    getWordLists(): Observable<WordList[]> {
        return this.afs.collection<WordList>('wordlists').valueChanges();
    }

    createWordList(name: string, words: string[]): Promise<DocumentReference> {
        return this.afs.collection('wordlists').add({name, words});
    }

    setWordList(name: string, words: string[]): Promise<void> {
        return this.afs.collection('wordlists').doc(name).set({name, words});
    }

    // Warning - this is a complete replacement update
    updateWordList(id: string, words: string[]): Promise<void> {
        return this.afs.collection('wordlists').doc(id).update({words});
    }

    // Use this if you need to setup a new database with the word lists
    setupDatabase() {
        this.setWordList('default', [...this.originalWords, ...this.duetWords]);
        this.setWordList('original', this.originalWords);
        this.setWordList('deepUndercover', this.deepUndercover);
        this.setWordList('duetWords', this.duetWords);
        this.setWordList('emojis', this.emojis);
        this.setWordList('pictures', this.getPicturesWordList());
        this.setWordList('tvWords', this.tvWords);
        this.setWordList('popCultureWords', this.popCultureWords);
        this.setWordList('thanksgiving', this.thanksgiving);
        this.setWordList('christmas', this.christmas);
        this.setWordList('mlk', this.mlk);
        this.setWordList('halloween', this.halloween);
    }

    private getPicturesWordList(): string[] {
        return [...Array(100).keys()].map(a => ('00' + a).slice(-2));
    }
}
