name: Deploy to Firebase

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Use Node.js version from .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install @angular/cli
        run: npm i -D -E @angular/cli --force
      - name: Install Ionic CLI 6.18.0
        run: npm install -g @ionic/cli@6.18.0
      - name: Install app dependencies
        run: npm ci --force
      - name: Install functions dependencies
        run: cd functions && npm i && cd ..
      - name: Build prod app
        run: npm run build:prod
      - uses: w9jds/firebase-action@master
        with:
          args: deploy -P prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
